### ISSUE TITLE
Error: getaddrinfo ENOTFOUND on Mac installation

### ISSUE THREAD

**Issue by CJDumbleton** [jvmahon/homebridge-smartshades#1]
Thanks for this smart shades homebridge plug-in. I've been looking for something like this for a while.

I've added the plug-in to my homebridge on my Mac. (It is my second homebridge plug-in.)

I see both the blinds I specified in the config file in my iOS Home app. But, when I try to raise the blind using the Home app, I get the following error in terminal:

`Error: getaddrinfo ENOTFOUND http://192.168.1.XXX
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)`

(I've replaced the last three digits of the IP address with XXX.)

Any suggestions? Thank you!

**Comment by jvmahon** [comment]
Hi,
I did a recent update on the code to fix a problem with the http interface in the NEO controller.  I had to switch to telnet and no longer use http. As a result, the setup instructions aren't clear. I'll update them within the next day or two and will post here when that is done.

**Comment by jvmahon** [comment]
Update the plugin using:
`````
npm -g install homebridge-smartshades
`````

Then take a look at the updated sample config.json. Your "host" should now be specified without the "http://" part - i.e., only the IP address is to be specified as show:
`````
"host":"127.0.0.1",
`````

Let me know if it now works for you.

**Comment by CJDumbleton** [comment]
Success.

I used the terminal command to update the plug-in. I amended the config file. I've tested using the iOS Home app to raise and lower both my blinds - it successfully raised and lowered them to the correct places.

Thanks. Now I'm going to play with iOS Home automations ...
