### ISSUE TITLE
After update, voice commands to Siri via homepod or phone do not function.

### ISSUE THREAD

**Issue by jameskooi** [jvmahon/homebridge-smartshades#11]
I LOVE this plug-in! Thank you so much to those of you supporting it. Anyone else having an issue with voice commands after the latest updates? If I open/close the blinds in the app by pressing the tile, it works great. But if I go and try and say "Hey Siri, close the living room blinds" it now responds with: "Sorry, that feature is not supported by your shades". Prior to the update that happened in the past 7-10 days, it worked great. 

Any ideas on troubleshooting? I tried to remove the motor type from the config file (cause my config file did not have that prior to the update) but it did not cause any change in the behavior.

Thanks again for the awesome plug-in and continuing to improve the set-up process! Hope I can get this figured out with a bit of guidance.

**Comment by jvmahon** [comment]
Did you also update to iOS 15.4?
I'm also having trouble after my iOS update.
Similar problems in other forums with shade control and iOS 15.4  (including for shades not using my plugin).
So its  a iOS problem, not the plugin.

**Comment by jameskooi** [comment]
You’re right! I did also update iOS. I am sorry to hear that it broke it for you too -_-. 

I will update all my devices to 15.4 and see if everything being on the same software version makes any difference. So far I haven’t had any luck. Thank you for the reply and giving me a better idea of what the issue is. Thanks again for making such a cool and useful plug-in!

**Comment by artfulsplodger** [comment]
Experiencing same issue here - anyone found a solution? Cheers!

**Comment by jvmahon** [comment]
Its not the plugin. Its an iOS bug introduced in 15.4. You'll have to wait until Apple fixes this bug.

**Comment by jameskooi** [comment]
For a (hopefully short term) work around, you can use the keyword “position” in Siri voice commands. 

So for example, if you say “Hey Siri, set the position of the bedroom blinds to open” it will open the bedroom blinds. 


This workaround has brought the reliability of the commands back up to the previous state before iOS 15.4 but obviously the voice command is significantly longer and less intuitive so hopefully the old voice commands will eventually work again once Apple fixes the bugs that were introduced!

**Comment by artfulsplodger** [comment]
Ok great thanks!


Oli
