### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by djayci** [jvmahon/homebridge-smartshades#6]
Hey there!

I'm trying to get your plugin to work but it just doesn't.
I can see traffic coming through homebridge as

Sent Command: 136.055-03-dn at time: 18:42:04

however, the blinds don't move a bit.
This is my config

"platform": "NEOShades",
"name": "NEOShades",
"host": "192.168.1.200", // I got this from the app
"controllerID": "2b0042000347393032323330", // I got this from the app too
"shades": [
{
"name": "Bedroom left blind",
"code": "136.055-01" //the blind ID from the app
},
{
"name": "Bedroom right blind",
"code": "136.055-03"
}
]

Any idea on how to debug it?

**Comment by jvmahon** [comment]
At first glance, the section of config.json that you posted looks correct. Please post the entire file so I can see it in context.

Please confirm - I assume you don't actually have the comments in the config.json file - correct?  You can't put comments in config.json.

Also, be sure to check the controllerID and host to make sure there isn't a typo.

Finally, double-check the host ID for your controller (I assume its using a dynamically assigned IP address -- check that it hasn't changed!)

**Comment by djayci** [comment]
That's correct, I just added the comments so it was easy for you to have a look.

The full config is as follows:
`{
    "bridge": {
        "name": "Homebridge B4DF",
        "username": "username",
        "port": 123,
        "pin": "123"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "email,
                "password": "password",
                "countryCode": "44",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "platform": "NEOShades",
            "name": "NEOShades",
            "host": "192.168.1.200",
            "controllerID": "2b0042000347393032323330",
            "shades": [
                {
                    "name": "Bedroom left blind",
                    "code": "136.055-01"
                },
                {
                    "name": "Bedroom right blind",
                    "code": "136.055-03"
                }
            ]
        }
    ]
}`

I've replaced a few fields so I don't expose my credentials.
I'm using the Neo Smart Blinds app. Got the blind codes and the controller ID and host IP from the app!

**Comment by djayci** [comment]
An update on this:

After a few tests, I can consistently close the blinds through homebridge but not open them. So, it only works when they are fully opened and I press the little button in the Home app.

It kind of tells us that the config is working as it can communicate with the controller, but for some reason it can only execute the down order
