### ISSUE TITLE
mysmartblinds issue

### ISSUE THREAD

**Issue by rnewhart** [jvmahon/homebridge-smartshades#7]
When I ask homekit to close mysmartblinds I get randomly on some shades:

[HOOBS 21EA@Target Position] The write handler for the characteristic 'Target Position' on the accessory 'Office Left' didn't respond at all!. Please check that you properly call the callback!

When I restarted the bridge I get this on all blinds
[HOOBS 21EA@Office Center@@Target Position] characteristic was supplied illegal value: number -1 exceeded minimum of 0

I installed 
Mysmartblinds Bridge
2.2.4 published 12/2/2020

There is no place to set target position in configuration

**Comment by jvmahon** [comment]
This plugin is specific to the NEO controller. See http://neosmartblinds.com/smartcontroller/ 

It is not intended for MySmartBlinds bridge.

**Comment by rnewhart** [comment]
Sorry.  I have a NEO smart blind also.  I was in the wrong section.
