### ISSUE TITLE
config.schema.json

### ISSUE THREAD

**Issue by boboxx** [jvmahon/homebridge-smartshades#8]
looks like the schema config for this plugin is the wrong config.... it's for Homebridge-HomeSeer4 Plugin.

**Comment by jvmahon** [comment]
You're right. I never did the schema for this one and mistakenly had copied one from another of my plugins.  I'll work on a schema for this, but it is likely a few weeks until I can get to it.

**Comment by jameskooi** [comment]
I got this working with the following configuration:

`{
    "platform": "NEOShades",
    "name": "NEOShades",
    "host": "192.1.1.1",
    "controllerID": "7AgJRY-3UAKLuwQqZJwAPA",
    "shades": [
        {
            "name": "Front",
            "code": "119.019-01"
        },
        {
            "name": "Right Side",
            "code": "119.019-02"
        },
        {
            "name": "Left Side",
            "code": "119.089-03"
        },
        {
            "name": "Basement Window",
            "code": "122.120-01"
        },
        {
            "name": "Left Bay",
            "code": "034.201-02"
        },
        {
            "name": "Middle Bay",
            "code": "034.201-03"
        },
        {
            "name": "Right Bay",
            "code": "034.201-04"
        },
        {
            "name": "Near Sink",
            "code": "034.201-01"
        },
        {
            "name": "Near Slider",
            "code": "034.201-05"
        },
        {
            "name": "Left Front",
            "code": "096.191-04"
        },
        {
            "name": "Middle Front",
            "code": "096.191-03"
        },
        {
            "name": "Right Front",
            "code": "096.191-02"
        },
        {
            "name": "Master Bathroom Window",
            "code": "163.292-01"
        },
        {
            "name": "Above Bed",
            "code": "101.172-02"
        },
        {
            "name": "Nursery Window",
            "code": "148.181-01"
        },
        {
            "name": "Front Wall",
            "code": "209.190-02"
        },
        {
            "name": "Side Wall",
            "code": "209.190-01"
        }
    ]
}`

**Comment by jvmahon** [comment]
Glad to hear its working for you. Closing this now.
